* Basic info

#+begin_src emacs-lisp
  (defun read-lines (filePath)
    "Return a list of lines of a file at filePath."
    (with-temp-buffer
      (insert-file-contents filePath)
      (split-string (buffer-string) "\n" t)))

  (if (file-exists-p "/home/user1/.emacs.d/name.txt")
      (let ((a (read-lines "/home/user1/.emacs.d/name.txt"))) 
	(let
	    ((name (car a))
	     (email (cadr a)))
	  (setq user-full-name name)
	  (setq user-mail-address email))))
#+end_src

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "David Larsson")
  (setq user-mail-address "david.larsson@selfhosted.xyz")
  ;; Assuming the Guix checkout is in ~/src/guix.
  (if (file-exists-p "~/src/guix/etc/copyright.el")
      (load-file "~/src/guix/etc/copyright.el"))
  ;;(load-file "~/src/guix/etc/copyright.el")
#+END_SRC

* Guix

#+BEGIN_SRC emacs-lisp
;; Assuming the Guix checkout is in ~/src/guix.
(with-eval-after-load 'geiser-guile
  (add-to-list 'geiser-guile-load-path "~/src/guix"))
;; Assuming the Guix checkout is in ~/src/guix.
(with-eval-after-load 'yasnippet
  (add-to-list 'yas-snippet-dirs "~/src/guix/etc/snippets"))
#+END_SRC

* Package repos, load paths etc.

(load "init.el")
ref https://github.com/itscaleb/emacs.d/blob/master/readme.org

;;  (setf custom-file "~/.emacs.d/emacs-custom.el")
;;  (load custom-file t)

In many cases you would need =(require 'myplugin)= instead of load:

Directory for installing and loading individual lisp-extensions:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/elisp-files/")
#+END_SRC

(add-to-list 'load-path "~/bin/webkit_emacs/")
;(load "webkit.el")

This subdir loading doesn't work :/

#+BEGIN_SRC emacs-lisp
(progn (cd "~/.emacs.d/elisp-files/")
              (normal-top-level-add-subdirs-to-load-path))
#+END_SRC

For MELPA elisp packages from http://melpa.milkbox.net/#/getting-started

#+BEGIN_SRC emacs-lisp
  ;;(require 'package)
  (add-to-list 'package-archives
	       '("melpa" . "https://melpa.org/packages/")
	       '("org" . "https://orgmode.org/elpa/")
	       )
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
;;  (require 'org-tempo)
;;  (load 'org-tempo)

#+END_SRC

Note potential conflict with company-mode, see [[https://github.com/joaotavora/yasnippet/issues/708][this issue]].

For the ~yas-inhibit-overlay-modification-protection~ part, see [[https://github.com/joaotavora/yasnippet/commit/fc33b2fbaee6c514c91e80f5b1c0210c776b03ed][this
link]].

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path
	       "~/.emacs.d/plugins/yasnippet")
  (setq yas-snippet-dirs
	'("~/.emacs.d/snippets"                 ;; personal snippets
	  ;;        "/path/to/some/collection/"           ;; foo-mode and bar-mode snippet collection
	  ;;        "/path/to/yasnippet/yasmate/snippets" ;; the yasmate collection
	  ))
  (yas-global-mode 1)
  (require 'yasnippet)
  (yas-global-mode 1)
  ;;(define-key yas-minor-mode-map [(tab)] nil)
  ;;(define-key yas-minor-mode-map (kbd "TAB") nil)
  (setq yas-inhibit-overlay-modification-protection t)
#+END_SRC


* Layout etc.

This only works in GUI mode

#+BEGIN_SRC emacs-lisp
(put 'upcase-region 'disabled nil)
(setq org-support-shift-select t)
(global-set-key (kbd "C-x C-<left>") 'shrink-window-horizontally)
(global-set-key (kbd "C-x C-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "C-x C-<down>") 'shrink-window)
(global-set-key (kbd "C-x C-<up>") 'enlarge-window)
#+END_SRC

Disable the menubar with menu-bar-mode 0. Menu bar is the File, Edit,
Options, Buffers, Tools, Emacs-Lisp, Help. You can always toggle
(switch between on or off) with this command M-x menu-bar-mode or F10.

arg >= 1 enables the menu bar. 

=(scroll-bar-mode -1)= to disable buffer scroll bars

#+BEGIN_SRC emacs-lisp
(menu-bar-mode 1)
(setq inhibit-startup-message t)
(setq inhibit-startup-echo-area-message t)
(tool-bar-mode -1)
;;(scroll-bar-mode -1)
#+END_SRC

* Possibly Old stuff

Weechat sucks so won't use =(require 'weechat)= or =(require
'weechat-alert)= anymore.

Alert is used to get alerts! Quack.el I don't know!

#+BEGIN_SRC emacs-lisp
(load "quack.el")
;;(require 'alert)
#+END_SRC

Old: (org-alert weechat-alert weechat pdf-tools syslog-mode nlinum rainbow-delimiters ac-geiser auto-complete-pcmp auto-complete paredit geiser))))

* Custom

custom-set-variables was added by Custom. If you edit it by hand, you
could mess it up, so be careful. Your init file should contain only
one such instance. If there is more than one, they won't work right.

;; custom-set-faces was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.

#+BEGIN_SRC emacs-lisp
  ;; (custom-set-variables
  ;;  '(package-selected-packages
  ;;    (quote
  ;;     (ox-hugo ox-gfm org-alert syslog-mode nlinum rainbow-delimiters ac-geiser auto-complete-pcmp auto-complete paredit geiser))))
  ;; (custom-set-faces)
#+END_SRC

* Media - EMMS
; emms, see: https://www.gnu.org/software/emms/quickstart.html
;(add-to-list 'load-path "~/.emacs.d/elisp-files/emms/")
;(require 'emms-setup)
;(emms-standard)
;(emms-default-players)

; emms-player-mpd, see https://github.com/alezost/emms-player-mpv
;(add-to-list 'load-path "~/.emacs.d/elisp-files/emms-player-mpv/")
;(require 'emms-player-mpv)
;(add-to-list 'emms-player-list 'emms-player-mpv)

* pdf tools
; pdf-tools specific from https://github.com/politza/pdf-tools/issues/128


#+BEGIN_SRC emacs-lisp
  ;; ;;; Begin Code Here ;;;
  ;; (pdf-tools-install) ;;for view pdfs
  ;; (load "pdf-tools") ;;for spooling to pdf.

  ;; (setq TeX-view-program-selection '((output-dvi "Evince") ;; This is not necessary
  ;; (output-pdf "PDF Tools") ;; <-- THIS one
  ;; (output-html "xdg-open") ;; This is not necessary
  ;; ))
  ;; (require 'subr-x)
  ;; (defun th/pdf-view-revert-buffer-maybe (file)
  ;; (when-let ((buf (find-buffer-visiting file)))
  ;; (with-current-buffer buf
  ;; (when (derived-mode-p 'pdf-view-mode)
  ;; (pdf-view-revert-buffer nil t)))))

  ;; (add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
  ;; #'th/pdf-view-revert-buffer-maybe)
  ;; ;;; END CODE HERE;;;
#+END_SRC

* Programming
** general

browse-at-remote lets you open-in-a-browser the file that is open in
the buffer at the same line number you are currently at - occasionally
easier to see what changes you are doing than invoking ~git diff~, or
just faster to visit the file in the browser if you have already
cloned the repo locally.

#+begin_src emacs-lisp
  (require 'browse-at-remote)
  (global-set-key (kbd "C-c g g") 'browse-at-remote)
#+end_src

** Geiser

#+begin_src bash :session test
(with-eval-after-load 'geiser-guile
  (add-to-list 'geiser-guile-load-path "~/src/code_guile/random_git_repo"))
#+end_src

** flycheck / flymake

#+begin_src emacs-lisp
  (add-hook 'sh-mode-hook '(lambda () (flycheck-mode)))
  ;;(add-hook 'python-mode-hook '(lambda () (flycheck-mode)))

  ;; (when (load "flymake" t)
  ;;   (defun flymake-pylint-init ()
  ;;     (let* ((temp-file (flymake-init-create-temp-buffer-copy
  ;; 		       'flymake-create-temp-inplace))
  ;; 	   (local-file (file-relative-name
  ;; 			temp-file
  ;; 			(file-name-directory buffer-file-name))))
  ;;       (list "epylint" (list local-file))))
  ;;   (add-to-list 'flymake-allowed-file-name-masks
  ;; 	       '("\\.py\\'" flymake-pylint-init)))
#+end_src

** Perl
;(add-to-list 'load-path "~/.emacs.d/pde/")
;(load "pde-load")

** Paredit.

Automatically enable it with emacs lisp modes. From
https://www.emacswiki.org/emacs/ParEdit

#+BEGIN_SRC emacs-lisp
(autoload 'enable-paredit-mode "paredit" "Turn on pseudo-structural editing of Lisp code." t)
(add-hook 'emacs-lisp-mode-hook       #'enable-paredit-mode)
(add-hook 'eval-expression-minibuffer-setup-hook #'enable-paredit-mode)
(add-hook 'ielm-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-interaction-mode-hook #'enable-paredit-mode)
(add-hook 'scheme-mode-hook           #'enable-paredit-mode)
#+END_SRC

** Python

*** fix indent-offset error thing 
"Can't guess python-indent-offset, using defaults: 4". is an annoying warning. You can make it go away with:

#+begin_src emacs-lisp
(setq python-indent-guess-indent-offset nil)
#+end_src


*** jupyter-mode

#+begin_src emacs-lisp
;;(require 'company-jupyter)
;;(require 'company-jedi)
;;(require 'ob-ipython)
;;(add-to-list 'company-backends 'company-jupyter)
;;(add-to-list 'company-backends 'company-ob-ipython)
#+end_src


https://github.com/tmurph/jupyter-mode

#+begin_src emacs-lisp
  ;;(require 'jupyter)
  ;;(require 'ob-jupyter)
  ;;(add-to-list 'org-src-lang-modes '("jupyter" . fundamental))

  ;;(require 'company-jupyter)
  ;;(add-to-list 'company-backends 'company-jupyter)
#+end_src

*** ein

Instead try ein:

#+begin_src
(jedi-setup)

(require 'ein)
(require 'ein-loaddefs)
(require 'ein-notebook)
(require 'ein-subpackages)
(setq
;;ein:jupyter-default-server-command "/home/wyousef/Downloads/AAProgramsAA/anaconda3/envs/MyDefaultEnv/bin/jupyter"
;;ein:jupyter-default-notebook-directory "/home/wyousef/Downloads/ZZPythonTryingZZ/code"
ein:completion-backend 'ein:use-ac-jedi-backend
)
#+end_src

or try ob-ipython

*** org-export to ipynb: ox-ipynb

And export to jupyter:

#+begin_src emacs-lisp
  (require 'ox-ipynb)
#+end_src

*** flymake-python-pyflakes and eldoc

Usage:

  (require 'flymake-python-pyflakes)
  (add-hook 'python-mode-hook 'flymake-python-pyflakes-load)

To use "flake8" instead of "pyflakes", add this line:

  (setq flymake-python-pyflakes-executable "flake8")

You can pass extra arguments to the checker program by customizing
the variable `flymake-python-pyflakes-extra-arguments', or setting it
directly, e.g.

  (setq flymake-python-pyflakes-extra-arguments '("--ignore=W806"))

Uses flymake-easy, from https://github.com/purcell/flymake-easy


Requires to install rope-read-mode from melpa.

#+begin_src emacs-lisp
  ;; (defun rope-eldoc-function ()
  ;;   (interactive)
  ;;   (let* ((win-conf (current-window-configuration))
  ;;          (resize-mini-windows nil)
  ;;          (disable-python-trace t)
  ;;          class fun args result-type
  ;;          (flymake-message (python-flymake-show-help))
  ;;          (initial-point (point))
  ;;          (paren-range (let (tmp)
  ;;                         (ignore-errors
  ;;                           (setq tmp (vimpulse-paren-range 0 ?\( nil t))
  ;;                           (if (and tmp (>= (point) (car tmp)) (<= (point) (cadr tmp)))
  ;;                               tmp
  ;;                             nil))))
  ;;          (result (save-excursion
  ;;                    ;; check if we on the border of args list - lparen or rparen
  ;;                    (if paren-range
  ;;                        (goto-char (car paren-range)))
  ;;                    (call-interactively 'rope-show-doc)
  ;;                    (set-buffer "*rope-pydoc*")
  ;;                    (goto-char (point-min))
  ;;                    (if (or (equal (point-max) 1)
  ;;                            (not (re-search-forward "\\([a-zA-Z_]+[a-zA-Z0-9_]*\\)(.*):" (point-at-eol) t))
  ;;                            (and (current-message) (string-match-p "BadIdentifierError" (current-message))))
  ;;                        nil
  ;;                      (let (result)
  ;;                        ;; check if this is class definition
  ;;                        (if (looking-at "class \\([a-zA-Z_]+[a-zA-Z0-9_]*\\)(.*):")
  ;;                            (progn
  ;;                              (goto-char (point-at-eol))
  ;;                              (re-search-forward (buffer-substring (match-beginning 1) (match-end 1)))))
  ;;                        (goto-char (point-at-bol))
  ;;                        (setq result (buffer-substring (point) (point-at-eol)))

  ;;                        ;; check if exist better description of function
  ;;                        (goto-char (point-at-eol))
  ;;                        (string-match "\\([a-zA-Z_]+[a-zA-Z0-9_]*\\)(.*)" result) ;get function name
  ;;                        (if (re-search-forward (concat (match-string 1 result) "(.*)") nil t)
  ;;                            (progn
  ;;                              (goto-char (point-at-bol))
  ;;                              (setq result (buffer-substring (point) (point-at-eol)))))

  ;;                        ;; return result
  ;;                        result
  ;;                        ))))
  ;;          (arg-position (save-excursion
  ;;                          (if paren-range
  ;;                              (count-matches "," (car paren-range) (point))))))
  ;;     ;; save window configuration
  ;;     (set-window-configuration win-conf)
  ;;     ;; process main result
  ;;     (if result
  ;;         (progn
  ;;           (setq result-type (nth 1 (split-string result "->")))
  ;;           (setq result (nth 0 (split-string result "->")))
  ;;           (setq result (split-string result "("))
  ;;           (setq fun (nth 1 (split-string (nth 0 result) "\\.")))
  ;;           (setq class (nth 0 (split-string (nth 0 result) "\\.")))
  ;;           ;; process args - highlight current function argument
  ;;           (setq args (nth 0 (split-string (nth 1 result) ")")))

  ;;           ;; highlight current argument
  ;;           (if args
  ;;               (progn
  ;;                 (setq args (split-string args ","))
  ;;                 (setq args (let ((num -1))
  ;;                              (mapconcat
  ;;                               (lambda(x)(progn
  ;;                                           (setq num (+ 1 num))
  ;;                                           (if (equal num arg-position) (propertize x 'face 'eldoc-highlight-function-argument) x)))
  ;;                               args
  ;;                               ",")))))

  ;;           ;; create string for type signature
  ;;           (setq result
  ;;                 (concat
  ;;                  (propertize "Signature: " 'face 'flymake-message-face)

  ;;                  (if fun
  ;;                      (concat (propertize (org-trim class) 'face 'font-lock-type-face)
  ;;                              "."
  ;;                              (propertize (org-trim fun) 'face 'font-lock-function-name-face))
  ;;                    (propertize (org-trim class) 'face 'font-lock-function-name-face))

  ;;                  " (" args ")"

  ;;                  (if result-type
  ;;                      (concat " -> " (org-trim result-type)))
  ;;                  ))))

  ;;     ;; create final result
  ;;     (if (and (null flymake-message) (null result))
  ;;         nil
  ;;       (concat flymake-message
  ;;               (if (and result flymake-message) "\n")
  ;;               result))))

  ;; (defvar disable-python-trace nil)

  ;; (defadvice message(around message-disable-python-trace activate)
  ;;   (if disable-python-trace
  ;;       t
  ;;     ad-do-it))

  ;; (defface flymake-message-face
  ;;   '((((class color) (background light)) (:foreground "#b2dfff"))
  ;;     (((class color) (background dark))  (:foreground "#b2dfff")))
  ;;   "Flymake message face")

  ;; (defun python-flymake-show-help ()
  ;;   (when (get-char-property (point) 'flymake-overlay)
  ;;     (let ((help (get-char-property (point) 'help-echo)))
  ;;       (if help
  ;;           (format (concat (propertize "Error: " 'face 'flymake-message-face) "%s") help)))))
  ;; ;; to enable
  ;; (set (make-local-variable 'eldoc-documentation-function) 'rope-eldoc-function)
  ;; (require 'flymake-python-pyflakes)
  ;; (add-hook 'python-mode-hook 'flymake-python-pyflakes-load)
  ;; (setq flymake-python-pyflakes-executable "flake8")
#+end_src

#+RESULTS:
: flake8


*** jedi.el

Python auto-complete with jedi.el. Add --sys-path <file-dir> to
jedi-mode startup so that functions from imports that are in relative
path to the current filename also show up in auto-complete etc.

,#+begin_src emacs-lisp
  ;; (setq jedi:server-args
  ;;       '("--sys-path" "/home/user1/src/code_python/ipstocidrdir"))
  (defun my-jedi-server-setup ()
    (let* ((filedir
	    (if (string-match "\*Org Src" (buffer-name (current-buffer)))
		(file-name-directory (buffer-file-name (org-src-source-buffer)))	
	      (file-name-directory (buffer-file-name (current-buffer)))))
	   (args (list "--sys-path" filedir))
	  )
      (set (make-local-variable 'jedi:server-args) args)))
  (add-hook 'python-mode-hook 'my-jedi-server-setup)
  ;;(setq jedi:complete-on-dot t)                 ; optional
  (add-hook 'python-mode-hook 'jedi:setup)
,#+end_src


#+RESULTS:


#+begin_src emacs-lisp
  ;; (setq jedi:server-args
  ;;       '("--sys-path" "/home/user1/src/code_python/ipstocidrdir"))
  (defun my-jedi-server-setup ()
    (let* ((filedir
	    (if (string-match "\*Org Src" (buffer-name (current-buffer)))
		(let* (
		       (fnd-arg (buffer-file-name (org-src-source-buffer)))
		       )
		  (if (stringp fnd-arg)
		      (file-name-directory (buffer-file-name (org-src-source-buffer)))
		    ""
		    ))
	      (let
		  ((fnd-arg (buffer-file-name (current-buffer))))
		(if (stringp fnd-arg)
		    (file-name-directory fnd-arg)
		  ""
		  ))
	      ))
	   (args (list "--sys-path" filedir))
	   )
      (if (string-match ".+" filedir)
	  (set (make-local-variable 'jedi:server-args) args))))
  (add-hook 'python-mode-hook 'my-jedi-server-setup)
  ;;(setq jedi:complete-on-dot t)                 ; optional
  (add-hook 'python-mode-hook 'jedi:setup)
#+end_src

#+RESULTS:
: /home/user1/VirtualHome/src/my-emacs-config/


Also start jedi-mode when in org-mode files. Since ~C-c .~ is taken in
org-mode we add another key-binding for
goto-definition/documentation-at-point, and create a hook to restore
the org-time-stamp binding of ~C-c .~.

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'my-jedi-server-setup)
  (add-hook 'org-mode-hook 'jedi:setup)
  (define-key org-mode-map (kbd "C-c d") 'jedi:goto-definition)
  (add-hook 'python-mode-hook '(lambda () (define-key python-mode-map (kbd "C-c d") 'jedi:goto-definition )))
  (add-hook 'org-mode-hook '(lambda () (define-key org-mode-map (kbd "C-c .") 'org-time-stamp)))
#+end_src


#+RESULTS:

** php

See under PHP Support [[https://www.emacswiki.org/emacs/ElDoc][here]].

#+begin_src emacs-lisp
(require 'xml)

(setq my-php-function-doc-hash (make-hash-table :test 'equal))


(defun my-php-fetch-function-doc (function)
  (let ((doc (gethash function my-php-function-doc-hash 'nope)))
    (when (eq doc 'nope)
      (setq doc nil)

      (let ((buf (url-retrieve-synchronously (concat "http://php.net/manual-lookup.php?pattern=" function))))
        (with-current-buffer buf
          (goto-char (point-min))
          (let (desc)
            (when (re-search-forward "<div class=\"methodsynopsis dc-description\">\\(\\(.\\|\n\\)*?\\)</div>" nil t)
              (setq desc
                    (replace-regexp-in-string
                     " +" " "
                     (replace-regexp-in-string
                      "\n" ""
                      (replace-regexp-in-string "<.*?>" "" (match-string-no-properties 1)))))
              
              (when (re-search-forward "<p class=\"para rdfs-comment\">\\(\\(.\\|\n\\)*?\\)</p>" nil t)
                (setq desc
                      (concat desc "\n\n"
                              (replace-regexp-in-string
                               " +" " "
                               (replace-regexp-in-string
                                "\n" ""
                                (replace-regexp-in-string "<.*?>" "" (match-string-no-properties 1))))))))

            (if desc
                (setq doc (xml-substitute-special desc)))))

        (kill-buffer buf))

      (puthash function doc my-php-function-doc-hash))

    doc))


(defun my-php-eldoc-function ()
  (let ((symbol (thing-at-point 'symbol)))
    (if (and symbol
             (not (eq (elt symbol 0) ?$)))
        (my-php-fetch-function-doc symbol))))
#+end_src

#+RESULTS:
: my-php-eldoc-function


** emacs-lisp

See [[https://www.emacswiki.org/emacs/ElDoc][here]].

#+begin_src emacs-lisp
  (define-minor-mode my-contextual-help-mode
    "Show help for the elisp symbol at point in the current *Help* buffer.

  Advises `eldoc-print-current-symbol-info'."
    :lighter " C-h"
    :global t
    (require 'help-mode) ;; for `help-xref-interned'
    (when (eq this-command 'my-contextual-help-mode)
      (message "Contextual help is %s" (if my-contextual-help-mode "on" "off")))
    (and my-contextual-help-mode
	 (eldoc-mode 1)
	 (if (fboundp 'eldoc-current-symbol)
	     (eldoc-current-symbol)
	   (elisp--current-symbol))
	 (my-contextual-help :force)))

  (defadvice eldoc-print-current-symbol-info (before my-contextual-help activate)
    "Triggers contextual elisp *Help*. Enabled by `my-contextual-help-mode'."
    (and my-contextual-help-mode
	 (derived-mode-p 'emacs-lisp-mode)
	 (my-contextual-help)))

  (defvar-local my-contextual-help-last-symbol nil
    ;; Using a buffer-local variable for this means that we can't
    ;; trigger changes to the help buffer simply by switching windows,
    ;; which seems generally preferable to the alternative.
    "The last symbol processed by `my-contextual-help' in this buffer.")

  (defun my-contextual-help (&optional force)
    "Describe function, variable, or face at point, if *Help* buffer is visible."
    (let ((help-visible-p (get-buffer-window (help-buffer))))
      (when (or help-visible-p force)
	(let ((sym (if (fboundp 'eldoc-current-symbol)
		       (eldoc-current-symbol)
		     (elisp--current-symbol))))
	  ;; We ignore keyword symbols, as their help is redundant.
	  ;; If something else changes the help buffer contents, ensure we
	  ;; don't immediately revert back to the current symbol's help.
	  (and (not (keywordp sym))
	       (or (not (eq sym my-contextual-help-last-symbol))
		   (and force (not help-visible-p)))
	       (setq my-contextual-help-last-symbol sym)
	       sym
	       (save-selected-window
		 (help-xref-interned sym)))))))

  (defun my-contextual-help-toggle ()
    "Intelligently enable or disable `my-contextual-help-mode'."
    (interactive)
    (if (get-buffer-window (help-buffer))
	(my-contextual-help-mode 'toggle)
      (my-contextual-help-mode 1)))

  (my-contextual-help-mode 1)

  (global-set-key (kbd "C-c h") #'my-contextual-help-toggle)
#+end_src

#+RESULTS:
: my-contextual-help-toggle


** Auto-Complete

Dirty fix for having AC everywhere

#+BEGIN_SRC emacs-lisp
(define-globalized-minor-mode real-global-auto-complete-mode
  auto-complete-mode (lambda ()
		       (if (not (minibufferp (current-buffer)))
			   (auto-complete-mode 1))))
(real-global-auto-complete-mode t)
#+END_SRC

Geiser-AC. Automatically enable ac-geiser.

#+BEGIN_SRC emacs-lisp
(require 'ac-geiser)
(add-hook 'geiser-mode-hook 'ac-geiser-setup)
(add-hook 'geiser-repl-mode-hook 'ac-geiser-setup)
(eval-after-load "auto-complete"
    '(add-to-list 'ac-modes 'geiser-repl-mode))
#+END_SRC


;(define-key geiser-repl-mode-keymap (kbd "C-.") 'geiser-doc-symbol-at-point)
;(define-key geiser-mode-keymap (kbd "C-,") nil)

** Javascript

js2-mode https://emacs.cafe/emacs/javascript/setup/2017/04/23/emacs-setup-javascript.html
https://truongtx.me/2014/04/20/emacs-javascript-completion-and-refactoring

#+BEGIN_SRC emacs-lisp
  (require 'js2-mode)
  (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
  ;; Better imenu
  (add-hook 'js2-mode-hook #'js2-imenu-extras-mode)
#+END_SRC

tern and company-mode
https://emacs.cafe/emacs/javascript/setup/2017/05/09/emacs-setup-javascript-2.html
you may want to invoke tern-server manually with 'tern &' in a
terminal

#+BEGIN_SRC emacs-lisp
(require 'js2-mode)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))

;; Better imenu
(add-hook 'js2-mode-hook #'js2-imenu-extras-mode)

(require 'company-tern)

(add-to-list 'company-backends 'company-tern)
(add-hook 'js2-mode-hook (lambda ()
			   (tern-mode)
			   (company-mode)))

;; Disable completion keybindings, as we use xref-js2 instead
(define-key tern-mode-keymap (kbd "M-.") nil)
(define-key tern-mode-keymap (kbd "M-,") nil)

(add-hook 'js-mode-hook (lambda () (tern-mode t)))
(eval-after-load 'tern
  '(progn
     (require 'tern-auto-complete)
           (tern-ac-setup)))
(defun delete-tern-process ()
  (interactive)
  (delete-process "Tern"))

(add-hook 'js2-mode-hook 'ac-js2-setup-auto-complete-mode)
(setenv "PATH" (concat "/usr/local/bin:" (getenv "PATH")))
(setq ac-js2-evaluate-calls t)
#+END_SRC

* Org-mode

This hook updates the org-mode buffer if the file has changed from
outside of org-mode. This is useful if for example you would update an
org-mode agenda file via say ical2org script/cronjob:

#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'auto-revert-mode)
#+end_src

** Variables

[[https://emacs.stackexchange.com/a/46043/28784][Reference]]

Orgmode's export function copies the buffer content to a new buffer
and evaluates the source blocks in the new buffer. Thereby only buffer
local variables with prefixes org- and orgtbl- are copied from the
original buffer to the new one.

That means you need to prefix your buffer local variables with org- or
orgtbl-.

In order to avoid clashes between org variables and your own buffer
local variables I suggest to use some unique id at the second position
of the name, e.g., org-my-....

I did not find a simple inline substitution of local variables by
their evaluation result. The closest one gets is inline source code
src_emacs-lisp[:var baz=org-my-foo]{baz}. The problem is that the
:exports header argument does not work for inline source code. So you
cannot suppress the source code.

For that reason I defined a new eval: link type with the following
elisp code.

#+begin_src emacs-lisp
(defun my-org-link-eval (path &rest _rest)
  "Evaluate PATH and return result as string."
  (condition-case err
      (prin1-to-string (eval (read path)))
    (error (format "Error in eval of %S: %S." path err))))

(defun my-org-link-eval-activate (start end path bracketp)
  "Display text from START to END as result of the eval of PATH.
BRACKETP is ignored."
  (save-excursion
    (if org-descriptive-links
      (add-text-properties
       start end
       (list 'display (propertize (my-org-link-eval path) 'face 'org-link)))
      (remove-text-properties start end '(display nil)))))

(org-link-set-parameters "val"
             :export #'my-org-link-eval
             :activate-func #'my-org-link-eval-activate)
#+end_src

If you install that code in your init file and restart emacs you can
use the following org file as a demo for all your contexts.

Context 1:
#+begin_example
,* First Section
is about [[val:org-my-foo]]
#+end_example

#+begin_example
Context 2:

#+BEGIN_SRC python :var baz=(prin1-to-string org-my-foo) :exports results
return(baz)
#+END_SRC

#+RESULTS:
: bar
#+end_example

#+begin_example
Context 3:

| Numbers | NumbersMultipliedBy2 |
|---------+----------------------|
|      32 |                   64 |
#+TBLFM: $1='(prin1-to-string org-my-aNumber)::$2=@2$1 * 2
#+end_example

#+begin_example
# Local Variables:                                             
# mode: org
# org-my-foo: bar
# org-my-aNumber: 32                                                     
# End:
#+end_example

With descriptive links activated [[eval:org-my-foo]] is displayed as
bar. Independently of the display the link always exports to bar.

The header argument :var baz=(prin1-to-string org-my-foo) of the
python source block evaluates org-my-foo in the course of function
argument evaluation and formats the resulting value as string. The
resulting string is assigned to the python variable baz.

The '(prin1-to-string org-my-aNumber) in the table formula evaluates
the lisp form (prin1-to-string org-my-aNumber) in the same way as in
the previous paragraph.

** Key-bindings

The kbd version below is because the \C-cl version doesn't work.

#+BEGIN_SRC emacs-lisp
  ;; (add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))
  ;; https://orgmode.org/manual/Activation.html#Activation
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cc" 'org-capture)
  (global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC

** todo-keywords setup

Org-mode todo - custom keywords instead of just TODO and DONE.

=Ctrl-c Ctrl-t= to select a new keyword for a header from list of
keywords. ~@~ is for note, ~!~ is for timestamp and the letter is for
the key used to select the TODO-item in question.

#+BEGIN_SRC emacs-lisp
  (setq org-todo-keywords
	(quote ((sequence "PROPOSED(p@/!)" "TODO(t)" "NEXT(n)" "STARTED(s)" "|" "DONE(d)")
		(sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)" "PHONE" "MEETING"))))
#+END_SRC

Define their colors

#+BEGIN_SRC emacs-lisp
  (setq org-todo-keyword-faces
	(quote (("TODO" :foreground "red" :weight bold)
		("PROPOSED" :foreground "yellow" :weight bold)
		("STARTED" :foreground "orange" :weight bold)
		("NEXT" :foreground "blue" :weight bold)
		("DONE" :foreground "forest green" :weight bold)
		("WAITING" :foreground "orange" :weight bold)
		("HOLD" :foreground "magenta" :weight bold)
		("CANCELLED" :foreground "forest green" :weight bold)
		("MEETING" :foreground "forest green" :weight bold)
                              ("PHONE" :foreground "forest green" :weight bold))))
#+END_SRC

Then we need to write the keywords to a file to be nice to the
org-schedule script that uses them:

#+begin_src emacs-lisp
 (defun write-string-to-file (string file)
   ;;(interactive "sEnter the string: \nFFile to save to: ")
   (with-temp-buffer
     (insert string)
     (when (file-writable-p file)
       (write-region (point-min)
                     (point-max)
                     file))))
#+end_src

#+RESULTS:
: write-string-to-file

The keywords should be written to file when org-mode is initialized:

#+begin_src emacs-lisp
  (defun todo-keywords-to-file()
    (write-string-to-file (mapconcat 'identity (mapcar 'car org-todo-keyword-faces) "\n") "~/.emacs.d/todokeywords.txt"))
  (add-hook 'org-mode-hook 'todo-keywords-to-file)
#+end_src

#+RESULTS:


You can also set these by:

#+BEGIN_SRC emacs-lisp
  (setq org-log-done t)
#+END_SRC


** Archiving
Org-mode archive - function/command to archive done tasks in a subtree

#+BEGIN_SRC emacs-lisp
  (defun org-archive-done-tasks ()
    (interactive)
    (org-map-entries
     (lambda ()
       (org-archive-subtree)
       (setq org-map-continue-from (outline-previous-heading)))
     "/DONE" 'tree))
#+END_SRC

;; Org-mode-AC. From https://github.com/aki2o/org-ac
;(require 'org-ac)
;; Make config suit for you. About the config item, eval the following sexp.
;(customize-group "org-ac")
;(org-ac/config-default)

; Org-pdfview, load automatically and configure the org-mode default open PDF file function.
#+BEGIN_SRC emacs-lisp
  (eval-after-load 'org '(require 'org-pdfview))
#+END_SRC
;(add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))

** Alert

Org-mode alert

#+BEGIN_SRC emacs-lisp
  (require 'org-alert)
  (setq org-alert-enable t)
  (setq alert-default-style 'libnotify)
  (setq org-alert-interval 300)
  (setq alert-fade-time 150)
#+END_SRC

** Calendar

#+BEGIN_SRC emacs-lisp
  (if (file-exists-p "~/.emacs.d/caldav-conf.el")
      (load-file "~/.emacs.d/caldav-conf.el"))
#+END_SRC

** Agenda

Org-Mode agenda

#+BEGIN_SRC emacs-lisp
  ;;'(org-agenda-files (quote ("~/org/notes.org" "~/org/work.org" "~/org/home.org")))
  (setq org-agenda-files (list "~/org/work.org"
			       "~/org/notes.org"
			       "~/org/home.org"
			       "~/org/fromhome.org"))
  ;;(add-hook 'after-init-hook 'org-agenda-list)
#+END_SRC

#+RESULTS:
| ~/org/work.org | ~/org/notes.org | ~/org/home.org | ~/org/fromhome.org |

** Contacts

Org-mode contacts

#+BEGIN_SRC emacs-lisp
  (require 'org-contacts)
  (setq org-contacts-files '("~/org/contacts.org" "~/org/other_contacts.org"))
  ;; (add-to-list 'org-capture-templates
  ;; '("c" "Contacts" entry (file "~/org/contacts.org")
  ;;   "* %(org-contacts-template-name)
  ;; :PROPERTIES:
  ;; :EMAIL: %(org-contacts-template-email)
  ;; :END:"))
#+END_SRC

#+RESULTS:

** Clock-table

Org-mode clock-table

https://orgmode.org/manual/Clocking-work-time.html#Clocking-work-time

Clock in with =C-c C-x C-i= and clock out with =C-c C-x C-o=.

#+BEGIN_SRC emacs-lisp
  (setq org-clock-persist 'history) ;; 
  (org-clock-persistence-insinuate)
  (define-key org-mode-map (kbd "C-c C-x C-i") 'org-clock-in)
  ;; For clocktable reports in the org-file itself
  (setq org-clock-clocktable-default-properties '(:maxlevel 10 :block thisweek :link f :formula % :scope agenda-with-archives :step day :properties ("Prio") :stepskip0)) ;; https://orgmode.org/manual/The-clock-table.html and https://emacs.stackexchange.com/questions/3166/clock-table-details-in-org-mode 
  ;; For clocktable report in Agenda-view
  (setq org-agenda-clockreport-parameter-plist (quote
						(:lang "se" :maxlevel 6 :fileskip0 t
                                                       :properties ("Prio")
                                                       :indent t :narrow 80!)))
#+END_SRC

** Babel

*** Languages

[[https://github.com/dzop/emacs-jupyter#overriding-built-in-src-block-languages][override python with jupyter-python]]

#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (ein . t)
     (dot . t)
     (latex . t)
     (shell . t)
     (ipython . t)
     (jupyter . t)))
  (setq org-confirm-babel-evaluate nil)
  (org-babel-jupyter-override-src-block "python")
#+END_SRC

** Alists

;; ref https://emacs.stackexchange.com/questions/12841/quickly-insert-source-blocks-in-org-mode

Below is all outdated because I'm using yasnippet instead.

Alist templates were updated with org-mode 9.2 so for now we need to
get the old template version back with =(require 'org-tempo)=.

Add header drawer with =<nhTAB=


#+BEGIN_SRC emacs-lisp
  ;; (require 'org-tempo)
  ;; (load 'org-tempo)
  ;; (defun tempo-use-tag-list (tag-list &optional completion-function)
  ;;   "Install TAG-LIST to be used for template completion in the current buffer.
  ;; TAG-LIST is a symbol whose variable value is a tag list created with
  ;; `tempo-add-tag'.

  ;; COMPLETION-FUNCTION is an obsolete option for specifyingis an optional
  ;; function or string that is used by `\\[tempo-complete-tag]' to find a
  ;; string to match the tag against. It has the same definition as the
  ;; variable `tempo-match-finder'. In this version, supplying a
  ;; COMPLETION-FUNCTION just sets `tempo-match-finder' locally."
  ;;   (let ((old (assq tag-list tempo-local-tags)))
  ;;     (if old
  ;; 	(setcdr old completion-function)
  ;;       (setq tempo-local-tags (cons (cons tag-list completion-function)
  ;; 				   tempo-local-tags))))
  ;;   (if completion-function
  ;;       (setq tempo-match-finder completion-function))
  ;;   (tempo-invalidate-collection))
#+END_SRC

#+RESULTS:
: org-tempo

#+BEGIN_SRC emacs-lisp
  ;; (tempo-define-template "foo"
  ;; 			 ;; template name
  ;; 		       '("System.out.println(\"foo\");")
  ;; 		       "f"
  ;; 		       )

      ;; (add-to-list 'org-structure-template-alist '("n" "#+NAME: ?"))
      ;; (add-to-list 'org-structure-template-alist '("hp" ":PROPERTIES:\n:header-args: ?\n:END:"))
      ;; (add-to-list 'org-structure-template-alist
      ;; 	       '("ns" "#+NAME: ?\n#+BEGIN_SRC \n\n#+END_SRC"))
#+END_SRC

Add language source blocks with =<s= plus first letter of language, so
for example bash would be added with =<sbTAB= and look like:

System.out.println("foo");

System.out.println("foo");



#+BEGIN_EXAMPLE
#+BEGIN_SRC bash
<cursor lands here>
#+END_SRC
#+END_EXAMPLE

For named source blocks you do the same but with =<nsbTAB= and so for
example bash would look like:

#+BEGIN_EXAMPLE
#+NAME: <cursor lands here>
#+BEGIN_SRC bash

#+END_SRC
#+END_EXAMPLE

#+BEGIN_SRC emacs-lisp
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("sb" "#+BEGIN_SRC bash\n?\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("sc" "#+BEGIN_SRC scheme\n?\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("sd" "#+BEGIN_SRC dot\n?\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("so" "#+BEGIN_SRC org\n?\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("sp" "#+BEGIN_SRC python\n?\n#+END_SRC"))
#+END_SRC

Named ones

#+BEGIN_SRC emacs-lisp
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("nsb" "#+NAME: ?\n#+BEGIN_SRC bash\n\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("nsc" "#+NAME: ?\n#+BEGIN_SRC scheme\n\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("nsd" "#+NAME: ?\n#+BEGIN_SRC dot\n\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("nso" "#+NAME: ?\n#+BEGIN_SRC org\n\n#+END_SRC"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("nsp" "#+NAME: ?\n#+BEGIN_SRC python\n\n#+END_SRC"))
#+END_SRC

Html stuff

The latter (below) will embed the html chunk as a block in the
rendered html page-not what you want; the former will export the html
chunk as is in the html file so that that code will be rendered when
the page is displayed-what you want.

;; ref https://stackoverflow.com/questions/9920001/including-literal-html-code-in-org-mode-templates

#+BEGIN_SRC emacs-lisp
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("eh" "#+BEGIN_EXPORT HTML\n?\n#+END_EXPORT"))
  ;; (add-to-list 'org-structure-template-alist
  ;; 	     '("h" "#+BEGIN_HTML\n?\n#+END_HTML"))
#+END_SRC

** Tangling & Misc

Tangle org files when we save them

#+BEGIN_SRC emacs-lisp
  (defun toggle-org-tangle-on-save ()
    (interactive)
    (if (bound-and-true-p org-tangle-on-save)
	(setq-local org-tangle-on-save nil)
      (setq-local org-tangle-on-save t))
    (message (if org-tangle-on-save "Enabled tangling on save" "Disabled tangling on save")))
#+END_SRC

To avoid having =_= be interpreted as subscripts when exporting
org-docs to html.

#+BEGIN_SRC emacs-lisp
  (setq org-use-sub-superscripts "{}")
#+END_SRC

Nice to have to not have to use the arrow-keys:

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c l") 'org-demote-subtree)
  (global-set-key (kbd "C-c r") 'org-promote-subtree)
#+END_SRC

To make automatic tangling work ~C-c C-v C-t~ without being prompted
for specific lisp Implementation

#+begin_src emacs-lisp
(setq geiser-default-implementation 'guile)
#+end_src

#+begin_src emacs-lisp
;;(setq org-src-preserve-indentation t)
#+end_src

* Presentation

https://gitlab.com/oer/org-re-reveal

[[https://github.com/yjwen/org-reveal/#set-the-location-of-revealjs][org-reveal set the local of reveal.js]]

# #+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js

#+name: reveal.js
#+begin_src emacs-lisp
;;(setq org-reveal-root "file:///home/user1/.emacs.d/reveal.js")
(require 'org-re-reveal)
;;(require 'org-reveal)
#+end_src

* Background and transparency

** Set a background image

Background image:

#+begin_src emacs-lisp
;; bg image
;; (custom-set-faces
;;       '(default ((t (:stipple nil :background ((image :type jpeg :file "~/18157421_1638024282892677_1528731701955746756_n.jpg") :origin display) :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 101 :width normal :family "misc-fixed")))))
#+end_src

** Transparency 

Note that this doesn't leave the text alone.

#+begin_src emacs-lisp
  ;;(set-frame-parameter (selected-frame) 'alpha '(<active> . <inactive>))
  ;;(set-frame-parameter (selected-frame) 'alpha <both>)

  ;; (set-frame-parameter (selected-frame) 'alpha '(50 . 0))
  ;; (add-to-list 'default-frame-alist '(alpha . (50 . 0)))
  ;;  (defun toggle-transparency ()
  ;;    (interactive)
  ;;    (let ((alpha (frame-parameter nil 'alpha)))
  ;;      (set-frame-parameter
  ;;       nil 'alpha
  ;;       (if (eql (cond ((numberp alpha) alpha)
  ;;                      ((numberp (cdr alpha)) (cdr alpha))
  ;;                      ;; Also handle undocumented (<active> <inactive>) form.
  ;;                      ((numberp (cadr alpha)) (cadr alpha)))
  ;;                100)
  ;;           '(50 . 0) '(100 . 100)))))
  ;; (global-set-key (kbd "C-c t") 'toggle-transparency)

  ;; Set transparency of emacs
  ;; (defun transparency (value)
  ;;   "Sets the transparency of the frame window. 0=transparent/100=opaque"
  ;;   (interactive "nTransparency Value 0 - 100 opaque:")
  ;;   (set-frame-parameter (selected-frame) 'alpha value))
#+end_src

* Backup files

Save the backup files ending with =~= to special directory. This is
nice so it doesn't clog up all directories in the filesystem.

#+BEGIN_SRC emacs-lisp
  (setq
   backup-by-copying t      ; don't clobber symlinks
   backup-directory-alist
    '(("." . "~/VirtualHome/MyEmacsBackups"))    ; don't litter my fs tree
   delete-old-versions t
   kept-new-versions 6
   kept-old-versions 2
   version-control t)       ; use versioned backups
  ;;(setq backup-directory-alist '(("." . "~/VirtualHome/MyEmacsBackups")))
#+END_SRC

* Misc

** Comment text keys

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c M-,") 'comment-region)
  (global-set-key (kbd "C-c M-.") 'uncomment-region)
#+END_SRC

Set default browser to chromium mainly because it handles reveal.js
slides well, so useful when running export-and-open.

#+BEGIN_SRC emacs-lisp
  (setq browse-url-browser-function 'browse-url-generic
	browse-url-generic-program "chromium")
#+END_SRC

** Move lines keys

#+BEGIN_SRC emacs-lisp
  (defun move-line-up ()
    "Move up the current line."
    (interactive)
    (transpose-lines 1)
    (forward-line -2)
    (indent-according-to-mode))
  (defun move-line-down ()
    "Move down the current line."
    (interactive)
    (forward-line 1)
    (transpose-lines 1)
    (forward-line -1)
    (indent-according-to-mode))
  (global-set-key [(meta shift n)]  'move-line-down)
  (global-set-key [(meta shift p)]  'move-line-up)
#+END_SRC

#+RESULTS:
: move-line-down

** Emacs as a pager

For emacs as pager, see
https://crowding.github.io/blog/2014/08/16/replace-less-with-emacs/

#+begin_src emacs-lisp
;; (server-start)
;; (unless (getenv "TERM_PROGRAM")
;;   (setenv "TERM" "xterm"))
;; (setenv "PAGER" "emacs-pager")
;; ; There was a weird interaction with Emacs’ builtin M-x man command. I worked around it with:
;; (defadvice man (around reset-pager activate)
;;   "reset PAGER to `less' when getting man pages."
;;   (let ((old (getenv "PAGER")))
;;     (setenv "PAGER" "less")
;;     ad-do-it
;;     (setenv "PAGER" old)))
#+end_src

* Continue here

;; PDF-TOOLS specific from https://github.com/politza/pdf-tools/issues/128
;; this is disabled because it slows down emacs loadtime significantly
;;; BEGIN CODE HERE ;;;
(pdf-tools-install) ;;for view pdfs
(load "pdf-tools") ;;for spooling to pdf.

(setq TeX-view-program-selection '((output-dvi "Evince") ;; This is not necessary
(output-pdf "PDF Tools") ;; <-- THIS one
(output-html "xdg-open") ;; This is not necessary
))

(require 'subr-x)
(defun th/pdf-view-revert-buffer-maybe (file)
(when-let ((buf (find-buffer-visiting file)))
(with-current-buffer buf
(when (derived-mode-p 'pdf-view-mode)
(pdf-view-revert-buffer nil t)))))

(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
#'th/pdf-view-revert-buffer-maybe)
;;; END CODE HERE;;;

;; Paredit. Automatically enable it with emacs lisp modes. From https://www.emacswiki.org/emacs/ParEdit
(autoload 'enable-paredit-mode "paredit" "Turn on pseudo-structural editing of Lisp code." t)
(add-hook 'emacs-lisp-mode-hook       #'enable-paredit-mode)
(add-hook 'eval-expression-minibuffer-setup-hook #'enable-paredit-mode)
(add-hook 'ielm-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-mode-hook             #'enable-paredit-mode)
(add-hook 'lisp-interaction-mode-hook #'enable-paredit-mode)
(add-hook 'scheme-mode-hook           #'enable-paredit-mode)

;; Geiser-AC. Automatically enable ac-geiser.
(require 'ac-geiser)
(add-hook 'geiser-mode-hook 'ac-geiser-setup)
(add-hook 'geiser-repl-mode-hook 'ac-geiser-setup)
(eval-after-load "auto-complete"
    '(add-to-list 'ac-modes 'geiser-repl-mode))


;; Org-mode-AC. From https://github.com/aki2o/org-ac
;(require 'org-ac)
;; Make config suit for you. About the config item, eval the following sexp.
;(customize-group "org-ac")
;(org-ac/config-default)

;; Org-pdfview, load automatically and configure the org-mode default open PDF file function.
(eval-after-load 'org '(require 'org-pdfview))
;(add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))

;; https://emacs.stackexchange.com/questions/30778/emacs-elisp-code-autocompletion-in-emacs-lisp-mode
(require 'ac-slime)
(add-hook 'slime-mode-hook 'set-up-slime-ac)
(add-hook 'slime-repl-mode-hook 'set-up-slime-ac)
(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'slime-repl-mode 'emacs-lisp-mode))

(defun ielm-auto-complete ()
  "Enables `auto-complete' support in \\[ielm]."
  (setq ac-sources '(ac-source-functions
		     ac-source-variables
		     ac-source-features
		     ac-source-symbols
		     ac-source-words-in-same-mode-buffers))
  (add-to-list 'ac-modes 'inferior-emacs-lisp-mode)
  (auto-complete-mode 1))
(add-hook 'ielm-mode-hook 'ielm-auto-complete)

(add-hook 'ielm-mode-hook #'enable-paredit-mode)
(add-hook 'ielm-mode-hook (lambda () (set (make-local-variable 'company-backends) '(company-elisp))))

(add-hook 'emacs-lisp-mode-hook #'enable-paredit-mode)
(add-hook 'emacs-lisp-mode-hook (lambda () (set (make-local-variable 'company-backends) '(company-elisp))))
(add-hook 'emacs-lisp-mode-hook 'ielm-auto-complete)

;(global-linum-mode)
(add-hook 'prog-mode-hook 'nlinum-mode)
(add-hook 'prog-mode-hook 'visual-line-mode)
(require 'pcmpl-args)
